server {
    server_name www.lycee-tcg.eu;
    rewrite ^/(.*)$ https://lycee-tcg.eu/$1;
}

#server {
#    # Permanent redirect to non-www
#    server_name www.domain.com;
#    rewrite ^/(.*)$ http://domain.com/$1 permanent;
#}
